### ISSUE TITLE
Error: querySrv ENOTFOUND

### ISSUE THREAD

**Issue by charliewang789** [risscasey/AppDevlopmentSummative#1]
Hi,

I am trying to run it, I got the following error - can you advise what can be wrong?

> appdevlopmentsummative@1.0.0 start D:\source\AppDevlopmentSummative
> nodemon -L server.js

[nodemon] 1.19.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] starting `node server.js`
application is running on port 3000
connection error: { Error: querySrv ENOTFOUND _mongodb._tcp.cw.mongodb.net
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:196:19)
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'querySrv',
  hostname: '_mongodb._tcp.cw.mongodb.net' }
(node:19940) UnhandledPromiseRejectionWarning: Error: querySrv ENOTFOUND _mongodb._tcp.cw.mongodb.net
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:196:19)
(node:19940) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19940) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by risscasey** [comment]
Hey there,

The issue will be with your connection to a mongoBD account inside of your config.json file (which you can duplicate from our config.exaple.json file) 

You are missing: 
- username 
- password 
- cluster name

Hopefully this helps although let me know otherwise ! (:

**Comment by majumdar-koushik** [comment]
In case of Mongo connection failure check if your IP has changed by googling “What is my IP”. Then add the new IP in Network access > IP Address list in Mongodb Atlas.
